name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup c++
      run: sudo apt-get install libgtest-dev cmake
    - name: test with c++
      run: cmake -B build -S .
          cmake --build build
          ctest --test-dir build --output-on-failure
          
