name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup c++
      run: sudo apt-get install libgtest-dev cmake
    - name: create build
      run: cmake -B build -S .
    - name: create build 2
      run: cmake --build build
    - name: run build
      run: ctest --test-dir build --output-on-failure
          
